### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by kento-pan** [kento-pan/Note-backups-with-SFTP#1]
Traceback (most recent call last):
  File "Projects\Note-backups-with-SFTP-master\main.py", line 191, in <module>
  File "lib\site-packages\pysftp\__init__.py", line 140, in __init__
  File "lib\site-packages\pysftp\__init__.py", line 176, in _start_transport
  File "lib\site-packages\paramiko\transport.py", line 416, in __init__
paramiko.ssh_exception.SSHException: Unable to connect to daemonc.duckdns.org: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[9152] Failed to execute script main

**Comment by kento-pan** [comment]
Bug fixed in commit 3920db8af85fa51d2e38cd2bcc6cda0230998672
